# Generated by Django 3.1.3 on 2021-01-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
