# Generated by Django 3.1.3 on 2021-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210125_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
